
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/crowbus?serverTimezone=UTC&chara
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: crowbus_dba
    password: crowbus

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher